[gh]
path = "releases"

# https://github.com/mvdan/sh/releases
[gh.tools.shfmt]
project = "mvdan/sh"
json = "shfmt.json"

# https://github.com/sharkdp/bat/releases
[gh.tools.batcat]
project = "sharkdp/bat"
json = "batcat.json"

# https://github.com/casey/just/releases
[gh.tools.just]
project = "casey/just"
json = "just-makelike.json"

# https://github.com/go-task/task/releases
[gh.tools.task]
project = "go-task/task"
json = "go-task.json"

# https://github.com/dandavison/delta
[gh.tools.delta]
project = "dandavison/delta"
json = "delta.json"

# https://github.com/charmbracelet/glow
[gh.tools.glow]
project = "charmbracelet/glow"
json = "glow.json"

# https://github.com/jesseduffield/lazygit
[gh.tools.lazygit]
project = "jesseduffield/lazygit"
json = "lazygit.json"

# https://shellcheck.net/
[gh.tools.shellcheck]
project = "koalaman/shellcheck"
json = "shellcheck.json"

# https://age-encryption.org/
[gh.tools.age]
project = "FiloSottile/age"
json = "age-encryption.json"

# https://github.com/junegunn/fzf
[gh.tools.fzf]
project = "junegunn/fzf"
json = "fzf.json"

# https://github.com/uncrustify/uncrustify
[gh.dev.uncrustify]
project = "uncrustify/uncrustify"
json = "uncrustify.json"

# https://github.com/watchexec/watchexec
[gh.tools.watchexec]
project = "watchexec/watchexec"
json = "watchexec.json"
