name: Update each project to latest version
run-name: ${{ github.actor }} updates each projects to latest version

on:
  schedule:
    - cron: '0 5 * * 0,2,3,4,6'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Cache checksums
      id: gh-cache
      uses: actions/cache@v4
      with:
        path: ~/.cache/gh-releases
        key: ${{ runner.os }}-gh-${{ hashFiles('releases/*.json') }}

    - name: Update files
      env:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      run: python -m ghrel gh-releases.toml --log INFO || true

    - name: Commit and push changes
      env:
        CI_USER_NAME: Laurent Boulard (CI)
        CI_USER_EMAIL: laurent.boulard@gmail.com
      run: |
        git config --local user.name "${{ env.CI_USER_NAME }}"
        git config --local user.email "${{ env.CI_USER_EMAIL}}"
        for project in $(git diff --diff-filter=D --name-only HEAD -- releases); do
          git add "$project"
          msg="Removing $project"
          echo "$msg"
          git commit -m "$msg"
        done
        for project in $(git diff --diff-filter=M --name-only HEAD -- releases); do
          git add "$project"
          msg="$(jq -r '"Update \(.project) to version \(.releases[0].tag|ltrimstr("v"))"' "$project")"
          echo "$msg"
          git commit -m "$msg"
        done
        for project in $(git ls-files -o HEAD -- releases); do
          git add "$project"
          msg="$(jq -r '"New \(.project) to version \(.releases[0].tag|ltrimstr("v"))"' "$project")"
          echo "$msg"
          git commit -m "$msg"
        done
        git push
